### ISSUE TITLE
Не могу дать репутацию

### ISSUE THREAD

**Issue by doctorixx** [iBuseWinner/Reputation#20]
Пишет, что даю самому себе

Вы не можете взаимодействовать с самим собой! 

(Но это другой игрок)

___

Конфиг:

```yml
database:
   # Тип хранения данных репутации игроков. SQL - локально в папке плагина; MYSQL - удалённая база данных
  type: 'SQL'
  url: 'localhost:3306'
  username: 'root'
  password: ''
  database: 'reputation'
  tableName: 'reputation'
  favoritesTableName: 'favorites'
  commandsTableName: 'commands'
  args: '?autoReconnect=true'

 # Количество игроков для топа /rep top и /rep top online
topAmount: 5
 # Максимально возможное количество репутации для выдачи другим игрокам. -1 - без ограничений. Право: reputation.max.название
maxReputation:
    default: -1

 # Звание, показывающееся игроку, достигшему определённого количества очков репутации
titles:
  0: 'Человек'

 # Разрешить ли отнимать игрокам репутацию друг у друга
takeReputation: false
 # Поставить true, если используете несколько серверов
bungeeMode: false
 # Репутация, устанавливаемая игроку при первом входе
defaultReputation: 1
 # Разрешить ли игроку взаимодействовать с репутацией при первом входе (/rep reject)
defaultAcceptReputation: true
 # Поставить true, если не хотите, чтобы игрок не мог выдавать +1 и -1 репутацию одному и тому же игроку
oneReputationPerPlayer: true
 # Разрешить ли отказываться от репутации
rejectReputation: false
color:
   # Изменение цвета репутации в зависимости от значения относительно нуля
  enable: false
   # Если репутация ниже нуля
  negativeReputation: '&c'
   # Если репутация равна нулю
  neutralReputation: '&7'
   # Если репутация выше нуля
  positiveReputation: '&a'

commands:
   # Изменение цвета репутации в зависимости от значения относительно нуля
  enable: false
  needs:
    - commands:
        - 'say У меня 5 очков репутации, ыы'
        - 'console!say у ${player_name} 5 очков репутации, ыы'
      id: '5'
      minReputation: 5
      oneTime: false

    - commands:
        - 'say я впервые достиг 10 очков репутации, поздравьте меня, пжшка!'
      id: '10'
      minReputation: 10
      oneTime: true

    - commands:
        - 'msg BlackBaroness пошли покушаем за счёт заведения'
      id: '500'
      minReputation: 500
      oneTime: false



```
